-- 포인트 시스템 스키마. DDL 의 단일 진실 원천이며 Hibernate 는 validate 로 매핑만 검증한다.
-- 실행 순서: 참조되는 테이블이 먼저 온다 (account -> transaction -> earning -> detail).

DROP TABLE IF EXISTS point_transaction_detail;
DROP TABLE IF EXISTS point_earning;
DROP TABLE IF EXISTS point_transaction;
DROP TABLE IF EXISTS point_account;

-- 회원 포인트 계정. 모든 포인트 변경 명령이 이 행을 잠그고 진행하는 직렬화 단위다.
CREATE TABLE point_account (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id   VARCHAR(64)  NOT NULL,
    max_balance BIGINT       NULL,
    created_at  TIMESTAMP    NOT NULL,
    CONSTRAINT uk_point_account_member UNIQUE (member_id),
    -- 한도를 두려면 최소 1 이다. 0 은 "한 푼도 못 받는 계정" 이라 서비스도 받지 않는다.
    CONSTRAINT ck_point_account_max_balance CHECK (max_balance IS NULL OR max_balance >= 1)
);

-- 거래. 외부에 노출하는 식별자(point_key) 단위이며 적립 · 적립취소 · 사용 · 사용취소가 모두 한 테이블에 쌓인다.
CREATE TABLE point_transaction (
    id                     BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    point_key              VARCHAR(32) NOT NULL,
    account_id             BIGINT      NOT NULL,
    type                   VARCHAR(16) NOT NULL,
    amount                 BIGINT      NOT NULL,
    order_no               VARCHAR(64) NULL,
    -- 사용 거래에만 채워 넣는다. 같은 주문의 이중 사용을 유일 제약으로 막기 위해 order_no 와 분리했다.
    use_order_no           VARCHAR(64) NULL,
    related_transaction_id BIGINT      NULL,
    created_at             TIMESTAMP   NOT NULL,
    CONSTRAINT uk_point_transaction_key UNIQUE (point_key),
    CONSTRAINT uk_point_transaction_use_order UNIQUE (account_id, use_order_no),
    CONSTRAINT fk_point_transaction_account FOREIGN KEY (account_id) REFERENCES point_account (id),
    CONSTRAINT fk_point_transaction_related FOREIGN KEY (related_transaction_id) REFERENCES point_transaction (id),
    CONSTRAINT ck_point_transaction_amount CHECK (amount > 0)
);

-- 적립 건. 잔액을 가진 단위이며 만료는 상태 컬럼이 아니라 expires_at 비교로 판정한다.
CREATE TABLE point_earning (
    id                           BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id                   BIGINT       NOT NULL,
    transaction_id               BIGINT       NOT NULL,
    kind                         VARCHAR(16)  NOT NULL,
    original_amount              BIGINT       NOT NULL,
    remaining_amount             BIGINT       NOT NULL,
    earned_at                    TIMESTAMP    NOT NULL,
    expires_at                   TIMESTAMP    NOT NULL,
    status                       VARCHAR(16)  NOT NULL,
    admin_id                     VARCHAR(64)  NULL,
    reason                       VARCHAR(200) NULL,
    reissued_from_transaction_id BIGINT       NULL,
    CONSTRAINT uk_point_earning_transaction UNIQUE (transaction_id),
    CONSTRAINT fk_point_earning_account FOREIGN KEY (account_id) REFERENCES point_account (id),
    CONSTRAINT fk_point_earning_transaction FOREIGN KEY (transaction_id) REFERENCES point_transaction (id),
    CONSTRAINT fk_point_earning_reissued_from FOREIGN KEY (reissued_from_transaction_id) REFERENCES point_transaction (id),
    CONSTRAINT ck_point_earning_original CHECK (original_amount > 0),
    CONSTRAINT ck_point_earning_remaining CHECK (remaining_amount >= 0 AND remaining_amount <= original_amount)
);

-- 거래 상세. "어떤 적립 건에서 어떤 주문으로 얼마가 나갔고 얼마가 돌아왔는지"를 1원 단위로 복원한다.
CREATE TABLE point_transaction_detail (
    id                 BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id     BIGINT      NOT NULL,
    earning_id         BIGINT      NOT NULL,
    amount             BIGINT      NOT NULL,
    direction          VARCHAR(8)  NOT NULL,
    reversed_detail_id BIGINT      NULL,
    seq                INT         NOT NULL,
    CONSTRAINT fk_point_detail_transaction FOREIGN KEY (transaction_id) REFERENCES point_transaction (id),
    CONSTRAINT fk_point_detail_earning FOREIGN KEY (earning_id) REFERENCES point_earning (id),
    CONSTRAINT fk_point_detail_reversed FOREIGN KEY (reversed_detail_id) REFERENCES point_transaction_detail (id),
    CONSTRAINT ck_point_detail_amount CHECK (amount > 0)
);

CREATE INDEX ix_point_earning_usable ON point_earning (account_id, status, expires_at);
CREATE INDEX ix_point_transaction_account ON point_transaction (account_id, created_at);
CREATE INDEX ix_point_detail_earning ON point_transaction_detail (earning_id);
CREATE INDEX ix_point_detail_reversed ON point_transaction_detail (reversed_detail_id);
